apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
    test: abc
spec:
  containers:
    - name: app
      image: hello-backend:v1
      imagePullPolicy: Never

      ports:
        - containerPort: 80
