apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
  annotations:
    kubernetes.io/change-cause: v4
spec:
  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend
        test: abcd
    spec:
      containers:
        - name: app
          image: hello-frontend:v4
          imagePullPolicy: Never
          ports:
            - containerPort: 80

          volumeMounts:
            - name: app-data
              mountPath: /data
              readOnly: false

      volumes:
        - name: app-local-data
          hostPath:
            path: /mnt/app-data

        - name: app-data
          persistentVolumeClaim:
            claimName: app-data
