apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    module: frontend
  ports:
    - protocol: TCP
      # internen port für den Cluster IP + port
      port: 80
      # Container Port
      targetPort: 80
      # Node port (extern, nur bei NodePort)
      nodePort: 32500
  type: NodePort
