apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  # replicas: 1

  selector:
    matchLabels:
      module: frontend

  template:
    metadata:
      name: frontend
      labels:
        module: frontend

    spec:
      containers:
        - name: frontend
          image: schulung-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
