services:
  frontend:
    image: frontend:1.0
    ports:
      - 8000:80

    volumes:
      - log_data:/data
      - hello_storage_data:/abcdef
    networks:
      - frontend-net

  backend:
    image: backend:1.0
    networks:
      - frontend-net
      - db-net

  db:
    container_name: db
    image: busybox
    command: sleep 1000
    networks:
      - db-net

volumes:
  log_data:

  hello_storage_data:
    external: true

networks:
  frontend-net:
  db-net:
