services:
  frontend:
    image: frontend:v1
    build: frontend
    depends_on:
      - backend
    ports:
      - $FE_PORT:80
    volumes:
      - ./frontend:/app

  backend:
    image: backend:v1
    # build: backend
