services:
  frontend:
    image: frontend:v1
    build: frontend
    depends_on:
      - backend
    ports:
      - 999:80

  backend:
    image: backend:v1
    build: backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 2s
      retries: 2
      start_period: 3s
