services:
  frontend:
    image: frontend:v2
    build:
      context: ./frontend
      args:
        - APP_VERSION=5.0
        - BUILD_APP_PASSWORD=my_secret
      # dockerfile: Dockerfile
    ports:
      - ${FE_PORT}:80

    environment:
      - MY_PASSWORD=${MY_PASSWORD}
      - APP_PASSWORD=${APP_PASSWORD}

    depends_on:
      - backend

    networks:
      - frontend-net

    deploy:
      resources:
        reservations:
          memory: 100mb
          cpus: "0.6"

  backend:
    image: backend:v1
    build: ./backend
    deploy:
      replicas: 2
    environment:
      MY_PASSWORD: ${MY_PASSWORD}

    volumes:
      - backend-data:/data

    networks:
      - frontend-net
      - db-net

  db:
    image: nginx

    networks:
      - db-net

volumes:
  backend-data:

networks:
  frontend-net:
  db-net:
