services:
  frontend:
    build:
      context: ./frontend
      args:
        - APP_VERSION=5.0
        - BUILD_APP_PASSWORD=my_secret
      # dockerfile: Dockerfile
    ports:
      - ${FE_PORT}:80

    environment:
      - MY_PASSWORD=${MY_PASSWORD}
      - APP_PASSWORD=${APP_PASSWORD}

    depends_on:
      - backend

  backend:
    build: ./backend
    deploy:
      replicas: 2

    environment:
      MY_PASSWORD: ${MY_PASSWORD}

    volumes:
      - ./data:/data
