apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: app
          image: hello-frontend:v2
          imagePullPolicy: Never

          ports:
            - containerPort: 80

          resources:
            limits:
              cpu: 20m
