apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
    - name: app
      image: hello-frontend:v1
      imagePullPolicy: Never

      ports:
        - containerPort: 80
