apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend

spec:
  replicas: 5

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: app
          image: hello-frontend:v3
          imagePullPolicy: Never

          ports:
            - containerPort: 80
