apiVersion: v1
kind: Pod
metadata:
  name: frontend-dev
  labels:
    app: frontend-dev
spec:
  containers:
    - name: app
      image: hello-frontend:v1
      imagePullPolicy: Never

      ports:
        - containerPort: 80

    - name: sidecar
      image: busybox
      args: ["sh", "-c", "while true; do ping localhost:80; sleep 3600; done"]
