version: "3.8"

services:
  frontend:
    build:
      context: frontend
      args:
        - module=backendtest
        - version=3.0
    ports:
      - ${FE_EXTERN_PORT}:${FE_INTERN_PORT}
    volumes:
      - ./frontend:/frontend
    environment:
      - FRONTEND_PORT=${FE_INTERN_PORT}
      - BACKEND_URL=http://backend:${BE_INTERN_PORT}

    env_file:
      - ./frontend/test.env

  backend:
    build: backend
    ports:
      - 81:80
    volumes:
      - ./backend:/backend
