version: "3.9"

services:
  frontend:
    # container_name: frontend
    # command: ["node", "AB"]
    image: frontend:v2
    build:
      context: frontend
      dockerfile: app.dockerfile
      args:
        - APP_VERSION=1.0
    ports:
      - 80:80
    environment:
      DB_SECRET: ${APP_DB_PASSWORD}

    volumes:
      - ./frontend:/app
      - app_data:/data

    env_file:
      - ${APP_ENV}

    networks:
      - frontend-network

  backend:
    # container_name: backend

    image: backend:v1
    build: backend
    ports:
      - "8080:80"
    environment:
      DB_SECRET: ${APP_DB_PASSWORD}

    volumes:
      - app_temp_volume:/data

    networks:
      - db-network
      - frontend-network

    mem_limit: 520m

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root

    networks:
      - db-network

volumes:
  app_data:
    external: true

  app_temp_volume:

networks:
  frontend-network:
  db-network:
