version: "3.8"

services:
  frontend:
    container_name: frontend
    build: .
    entrypoint: python frontend.py
    ports:
      - "8080:80"

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend.dockerfile
    command: python frontend.py
    ports:
      - "8081:80"
