apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
    - name: app
      image: backend:v1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
