apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      # labels of my frontend - pod
      app: frontend

  template:
    metadata:
      # name: frontend-sadsah
      labels:
        app: frontend
    spec:
      containers:
        - name: app
          image: frontend:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
