apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
    - name: app
      image: frontend:v1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80

    # - name: busybox
    #   image: yauritux/busybox-curl
    #   command:
    #     - curl
    #     - localhost:80;
