apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.projectName }}
  labels:
    app: {{ .Values.projectName }}
  annotations:
    kubernetes.io/change-cause: v4
spec:
  selector:
    matchLabels:
      app: {{ .Values.projectName }}

  template:
    metadata:
      labels:
        app: {{ .Values.projectName }}

    spec:
      containers:
        - name: app
          image: {{ .Values.image }}
          imagePullPolicy: Never
          ports:
            - containerPort: 80

          resources:
            limits:
              cpu: 20m
