apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    my-app: my-web

spec:
  containers:
    - name: app
      image: nginx

    - name: sidecar
      image: nginx
      args:
        [
          "sh",
          "-c",
          "while true; do echo 'Sidecar Container'; sleep 3600; done",
        ]
