services:
  frontend:
    image: frontend:latest

    deploy:
      replicas: 2
    ports:
      - 8000:80

    environment:
      - BACKEND_URL=http://backend:90

    volumes:
      - ./frontend:/app

    depends_on:
      - backend

  backend:
    image: backend:latest
    deploy:
      replicas: 2

    volumes:
      - ./backend:/app

    healthcheck:
      test: ["CMD", "curl", "localhost:90"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 1s
