apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend

spec:
  selector:
    matchLabels:
      my-app: hello
      my-tier: frontend

  template:
    metadata:
      labels:
        my-app: hello
        my-tier: frontend

    spec:
      containers:
        - name: app
          image: frontend:v2
          command:
            - sleep
            - 1000s
          imagePullPolicy: Never
          ports:
            - containerPort: 80

          resources:
            limits:
              cpu: 10m
