apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
    - name: app
      image: busybox:latest
      command:
        - sleep
        - 1000s

      volumeMounts:
        - name: local-storage
          mountPath: /data

    - name: app2
      image: busybox:latest
      command:
        - sleep
        - 1000s

      volumeMounts:
        - name: local-storage
          mountPath: /data

  volumes:
    - name: local-storage
      emptyDir: {}

    - name: node-storage
      hostPath:
        path: /mnt/pod-data
