apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.projectName }}-backend

spec:
  replicas: 5

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: app
          image: hello-backend:v1
          imagePullPolicy: Never

          ports:
            - containerPort: 80
