apiVersion: v1
kind: Service
metadata:
  name: frontend

spec:
  selector:
    app: frontend

  ports:
    - port: 80 # HTTP://FRONTEND:80
      targetPort: 80 # -> weitergeleitet an allen Prods unter 80
      nodePort: 32001

  type: NodePort
