apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend

spec:
  selector:
    matchLabels:
      my-app: hello
      my-tier: backend

  template:
    metadata:
      labels:
        my-app: hello
        my-tier: backend

    # test

    spec:
      containers:
        - name: app
          image: backend:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
