apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    module: frontend-app

spec:
  containers:
    - name: frontend
      image: coolapp-frontend:v1
      imagePullPolicy: IfNotPresent

      ports:
        - containerPort: 80
