apiVersion: v1
kind: Service
metadata:
  name: backend

spec:
  selector:
    app: backend

  ports:
    - port: 80 # HTTP://BACKEND:80
      targetPort: 80 # -> weitergeleitet an allen Prods unter 80
      nodePort: 32002

  type: NodePort
