services:
  frontend:
    image: frontend:1.0
    build:
      context: frontend
      dockerfile: app.Dockerfile
      tags:
        - "127.0.0.1:6000/frontend:1.0"

    depends_on:
      - backend

    ports:
      - 8000:80

  backend:
    image: backend:1.0
    build: backend
