services:
  frontend:
    image: frontend:2.0
    build:
      context: frontend
      dockerfile: app.Dockerfile

    depends_on:
      - backend

    deploy:
      replicas: 3

    ports:
      - 8000:80

  backend:
    image: backend:1.0
    build: backend
