services:
  frontend:
    # container_name: frontend
    build:
      context: ./frontend
      args:
        - APP_VERSION=5.0
        - ABCD=EFG
    image: 127.0.0.1:5000/frontend:v1
    ports:
      - 4000:80
    environment:
      BACKEND_URL: "http://localhost:4001"

    deploy:
      # restart_policy:
      #   condition: always
      replicas: 1
      resources:
        limits:
          cpus: "0.8"
          memory: 40m
          pids: 4

  backend:
    # container_name: backend
    build: ./backend
    # scale: 1
    image: 127.0.0.1:5000/backend:v1
    ports:
      - 40001:80

    # deploy:
    #   restart_policy:
    #     condition: unless-stopped
    #     delay: 10s
    # max_attempts: 100
