# ============================================================
# Ansible Inventory — hosts.yml
#
# YAML-Format — gleiches Konzept wie hosts.ini, aber in YAML.
#
# Struktur:
#   all:                     ← Wurzel-Gruppe (immer vorhanden)
#     children:              ← Untergruppen
#       servers:             ← eigene Gruppe "servers"
#         hosts:             ← Hosts in dieser Gruppe
#           server1:         ← Hostname / Alias
#             ...            ← Host-Variablen
#         vars:              ← Gruppen-Variablen
#           ...
#
# Verwendung:
#   ansible-playbook -i /inventory/hosts.yml playbook.yml
# ============================================================

all:
  children:
    servers:
      hosts:
        server1:
          ansible_host: 10.20.0.11
        server2:
          ansible_host: 10.20.0.12

      vars:
        ansible_user: root
        ansible_ssh_private_key_file: /root/.ssh/id_rsa
