services:
  frontend:
    image: hello-frontend
    ports:
      - "1000-1010:80"

    volumes:
      - ../frontend:/app
      - app_data:/data

    networks:
      - frontend-network

  backend:
    build: ../backend
    # ports:
    #   - "${BACKEND_PORT}:80"
    environment:
      BACKEND_PORT: ${BACKEND_PORT}

    networks:
      - frontend-network
      - db-network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    privileged: true

    networks:
      - db-network

  # dind:
  #   image: docker:dind

volumes:
  app_data:

networks:
  frontend-network:
  db-network:
