services:
  frontend:
    build:
      context: ../frontend
      args:
        - APP_DB_PASSWORD=${APP_DB_PASSWORD}
    ports:
      - "1000-1010:80"

    volumes:
      - ../frontend:/app
      - app_data:/data

  backend:
    build: ../backend
    ports:
      - "${BACKEND_PORT}:80"
    environment:
      BACKEND_PORT: ${BACKEND_PORT}

volumes:
  app_data:
